basePath: /
definitions:
  handlers.GenerateTokenRequest:
    properties:
      role:
        enum:
        - admin
        - user
        type: string
      user_id:
        type: string
    required:
    - role
    - user_id
    type: object
  handlers.GenerateTokenResponse:
    properties:
      token:
        type: string
    type: object
  models.ApplicableCoupon:
    description: ApplicableCoupon represents a coupon that is applicable to the current
      cart.
    properties:
      coupon_code:
        type: string
      discount:
        type: number
      discount_type:
        type: string
      discount_value:
        type: number
    type: object
  models.ApplicableCouponsRequest:
    description: ApplicableCouponsRequest represents the request to find applicable
      coupons for a cart
    properties:
      cart_items:
        items:
          $ref: '#/definitions/models.CartItem'
        type: array
      order_total:
        type: number
      timestamp:
        type: string
    required:
    - cart_items
    - order_total
    - timestamp
    type: object
  models.ApplicableCouponsResponse:
    description: ApplicableCouponsResponse represents the response body for applicable
      coupons.
    properties:
      applicable_coupons:
        items:
          $ref: '#/definitions/models.ApplicableCoupon'
        type: array
    type: object
  models.CartItem:
    description: CartItem holds cart items
    properties:
      category:
        type: string
      id:
        type: string
      price:
        type: number
      quantity:
        type: integer
    type: object
  models.CreateCouponRequest:
    description: CreateCouponRequest represents the request to create a new coupon
    properties:
      applicable_categories:
        items:
          type: string
        type: array
      applicable_medicine_ids:
        items:
          type: string
        type: array
      coupon_code:
        type: string
      discount_type:
        description: DiscountType is the type of discount (percentage or fixed_amount)
        enum:
        - percentage
        - fixed_amount
        type: string
      discount_value:
        type: number
      expiry_date:
        type: string
      max_total_usage:
        type: integer
      max_usage_per_user:
        type: integer
      min_order_value:
        type: number
      terms_and_conditions:
        type: string
      usage_type:
        enum:
        - one_time
        - multi_use
        - time_based
        type: string
      valid_time_window_end:
        type: string
      valid_time_window_start:
        type: string
    required:
    - coupon_code
    - discount_type
    - discount_value
    - expiry_date
    - usage_type
    type: object
  models.DiscountDetails:
    description: DiscountDetails represents the details of the discount applied by
      a coupon.
    properties:
      items_discount:
        type: number
      total_discount:
        type: number
    type: object
  models.ErrorResponse:
    description: ErrorResponse represents a generic error response with an error message
      and details.
    properties:
      details:
        type: string
      error:
        type: string
    type: object
  models.SuccessResponse:
    description: SuccessResponse represents a generic success response with a message.
    properties:
      message:
        type: string
    type: object
  models.ValidateCouponRequest:
    description: ValidateCouponRequest represents the request body for validating
      a coupon.
    properties:
      cart_items:
        items:
          $ref: '#/definitions/models.CartItem'
        type: array
      coupon_code:
        type: string
      order_total:
        type: number
      timestamp:
        type: string
    required:
    - cart_items
    - coupon_code
    - order_total
    - timestamp
    type: object
  models.ValidateCouponResponse:
    description: ValidateCouponResponse represents the response body for validating
      a coupon.
    properties:
      discount:
        $ref: '#/definitions/models.DiscountDetails'
      is_valid:
        type: boolean
      message:
        type: string
    type: object
info:
  contact: {}
  title: Coupon System API
  version: "1.0"
paths:
  /admin/coupons:
    post:
      consumes:
      - application/json
      description: Creates a new coupon with the provided details.
      parameters:
      - description: Coupon Data
        in: body
        name: coupon
        required: true
        schema:
          $ref: '#/definitions/models.CreateCouponRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Coupon created successfully
          schema:
            $ref: '#/definitions/models.SuccessResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a new coupon
      tags:
      - coupons
  /coupons/applicable:
    post:
      consumes:
      - application/json
      description: Retrieves a list of coupons applicable to the current cart.
      parameters:
      - description: Cart details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ApplicableCouponsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: List of applicable coupons
          schema:
            $ref: '#/definitions/models.ApplicableCouponsResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get applicable coupons
      tags:
      - coupons
  /coupons/validate:
    post:
      consumes:
      - application/json
      description: Validates a coupon code against the provided cart details.
      parameters:
      - description: Validation request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ValidateCouponRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Coupon validation result
          schema:
            $ref: '#/definitions/models.ValidateCouponResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Validate a coupon
      tags:
      - coupons
  /generate-tokens:
    post:
      consumes:
      - application/json
      description: Generates a JSON Web Token for a given user ID and role.
      parameters:
      - description: User ID and Role
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.GenerateTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: JWT generated successfully
          schema:
            $ref: '#/definitions/handlers.GenerateTokenResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Generate a JWT
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
